spring:
  datasource:
    url: jdbc:h2:~/data/hello-spring;AUTO_SERVER=true
    username: sa
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

---

spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:test
    username: sa
